# zsh promt
export VIRTUAL_ENV_DISABLE_Prompt=0

# golang env
export GOPATH=$HOME/.gopath
export PATH=$PATH:$GOPATH/bin

# minikube disable emoji
export MINIKUBE_IN_COLOR=false
export MINIKUBE_IN_STYLE=false

