PROMPT='[%F{red}%n%f@%F{27}%m %f%F{yellow}%1~%f]$ '

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/linh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

alias ls='ls --color=auto'
alias ll='ls -la'
alias lt='tree -C'

export GOPATH=$HOME/Project/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
