PROMPT='[%F{red}%n%f@%F{27}%m %f%F{yellow}%1~%f]$ '

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/linh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
