export TERM='xterm-256color'
PROMPT='[%F{red}%n%f@%F{blue}%m%f%F{yellow}%1~%f]$ '

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
